const images = {
  anggur: '/assets/anggur.png',
  avatar: '/assets/avatar.svg',
  avatarDark: '/assets/avatar-dark.svg',
  arrowLeft: '/assets/arrowLeft.svg',
  arrow_right:'/assets/arrow-right.svg',
  banner1: '/assets/banner1.png',
  banner2: '/assets/banner2.png',
  banner3: '/assets/banner3.png',
  bca: '/assets/bca.svg',
  bni: '/assets/bni.svg',
  cartOutline: '/assets/cart-outline.svg',
  close: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAA4AAAAPCAYAAADUFP50AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAADuSURBVHgBjdG9DoIwEAfwlhtYnZkcCSHEUTfcHCBh1M1NH8FNHsFH0DdgM07G0Q032BwdHV0A70xJ+Ggrl5CU436l+Rd83x95nrfJ8/zOBlQYhmvLsp7guu4Z37e2bTPENx0KgmDPOT+YpjkDx3EeVVUtsb/QYYFiXL4BYAVZlr0QX3S4g+ZJkqRAH3RYhqjPmztHUTQpiuKKyxENl2XJZKgHu1i0eojK6EIxcGy32ogKmDy9Hf0Jnw8+U1lgIEFxfTzDME6qtEGF6Hi6tEGF6g1VmOtQs7pXRanyf0hEm9KMCI3Xu43ZwMLZ3/1+AcEOqQnFtNzdAAAAAElFTkSuQmCC',
  cart: '/assets/cart.svg',
  downloadApp: '/assets/download-app.svg',
  EXAMPLE: '/assets/.svg',
  facebook: '/assets/facebook-icon.svg',
  gmail: '/assets/gmail-icon.svg',
  gopay: '/assets/gopay.svg',
  instagram: '/assets/instagram-icon.svg',
  linkaja: '/assets/linkaja.svg',
  logo: '/assets/logo.svg',
  logoWhite: '/assets/logoWhite.svg',
  logout: '/assets/logout.svg',
  mangga: '/assets/mangga.png',
  ovo: '/assets/ovo.svg',
  search: '/assets/search.svg',
};

export default images;