const actions = {
  ADD_CART: `ADD_CART`,
  ADD_USER: 'ADD_USER',
  DONE_LOADING: 'DONE_LOADING',
  FETCH_ORDERS: 'FETCH_ORDERS',
  FETCH_ORDER: 'FETCH_ORDER',
  FETCH_PREDICTIONS: 'FETCH_PREDICTIONS',
  FETCH_PRODUCT: 'FETCH_PRODUCT',
  FETCH_PRODUCTS: 'FETCH_PRODUCTS',
  FETCH_REPORTS: 'FETCH_REPORTS',
  FETCH_REPORT: 'FETCH_REPORT',
  FETCH_USERS: 'FETCH_USERS',
  FETCH_USER: 'FETCH_USER',
  LOADING: 'LOADING',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  SHOW_MODAL: (type) => `SHOW_MODAL_${type}`,
  HIDE_MODAL: (type) => `HIDE_MODAL_${type}`,
};

export default actions;