const product = [
  {
    id:1,
    name:'Anggur Merah',
    description: 'Anggur Merah Kualitas Premium',
    slug: 'anggur-merah',
    image: '/assets/anggur.png',
    price:45000,
    stock:10,
    unit:'kg',
    display_price: 'Rp. 45.000',
    display_full_price: 'Rp. 45.000/kg',
    discount:0,
  },
  {
    id: 2,
    name: 'Mangga Arum Manis',
    image: '/assets/mangga.png',
    description: 'Mangga Manis Semanis Senyum Kamu',
    slug:'mangga-manis',
    price: 20000,
    stock: 10,
    unit: 'kg',
    display_price: 'Rp. 20.000',
    display_full_price: 'Rp. 20.000/kg',
    discount: 0,
  },
  {
    id: 3,
    name: 'Jeruk Mandarin',
    image: '/assets/jeruk.png',
    description: 'Jeruk',
    slug: 'jeruk-mandarin',
    price: 23000,
    stock: 10,
    unit: 'kg',
    display_price: 'Rp. 23.000',
    display_full_price: 'Rp. 23.000/kg',
    discount: 25,
  },
  {
    id: 4,
    name: 'Jeruk Sunkist',
    image: '/assets/jeruk-sunkist.png',
    description: '',
    slug: 'jeruk-sunkist',
    price: 30000,
    stock: 15,
    unit: 'kg',
    display_price: 'Rp. 30.000',
    display_full_price: 'Rp. 30.000/kg',
    discount: 0,
  },
  {
    id: 5,
    name: 'Anggur Hitam',
    image: '/assets/anggur-hitam.png',
    description: '',
    slug: 'anggur-hitam',
    price: 63000,
    stock: 8,
    unit: 'kg',
    display_price: 'Rp. 63.000',
    display_full_price: 'Rp. 63.000/kg',
    discount: 0,
  },
  {
    id: 6,
    name: 'Alpukat Mentega',
    image: '/assets/alpukat-mentega.png',
    description: '',
    slug: 'alpukat-mentega',
    price: 21500,
    stock: 10,
    unit: 'kg',
    display_price: 'Rp. 21.500',
    display_full_price: 'Rp. 21.500/kg',
    discount: 0,
  },
  {
    id: 7,
    name: 'Melon',
    image: '/assets/melon.png',
    description: '',
    slug: 'melon',
    price: 10000,
    stock: 5,
    unit: 'kg',
    display_price: 'Rp. 10.000',
    display_full_price: 'Rp. 10.000/kg',
    discount: 0,
  },
  {
    id: 8,
    name: 'Pome',
    image: '/assets/pome.png',
    description: '',
    slug: 'pome',
    price: 25000,
    stock: 5,
    unit: 'kg',
    display_price: 'Rp. 25.000',
    display_full_price: 'Rp. 25.000/kg',
    discount: 0,
  },
  {
    id: 9,
    name: 'Pear',
    image: '/assets/pear.png',
    description: '',
    slug: 'pear',
    price: 21000,
    stock: 5,
    unit: 'kg',
    display_price: 'Rp. 21.000',
    display_full_price: 'Rp. 21.000/kg',
    discount: 0,
  },
  {
    id: 10,
    name: 'Persik',
    image: '/assets/persik.png',
    description: '',
    slug: 'persik',
    price: 18000,
    stock: 5,
    unit: 'kg',
    display_price: 'Rp. 18.000',
    display_full_price: 'Rp. 18.000/kg',
    discount: 0,
  },
  {
    id: 11,
    name: 'Duku',
    image: '/assets/duku.jpeg',
    description: '',
    slug: 'duku',
    price: 12000,
    stock: 10,
    unit: 'kg',
    display_price: 'Rp. 12.000',
    display_full_price: 'Rp. 12.000/kg',
    discount: 0,
  },
  {
    id: 12,
    name: 'Kiwi',
    image: '/assets/kiwi.png',
    description: '',
    slug: 'kiwi',
    price: 35000,
    stock: 10,
    unit: 'kg',
    display_price: 'Rp. 35.000',
    display_full_price: 'Rp. 35.000/kg',
    discount: 0,
  }
];

export default product;